apiVersion: v1
kind: ConfigMap
metadata:
  name: caterer-service-configmap
  labels:
    app: caterer-service
data:
  application.properties: |-
    spring.application.name=caterer-service
    management.endpoints.web.exposure.include=*

    spring.data.mongodb.host=mongo
    spring.data.mongodb.port=27017
    spring.data.mongodb.database=caterers

    spring.redis.host=redis
    spring.redis.port=6379
    spring.cache.redis.cache-null-values=false
    spring.cache.redis.time-to-live=600000

    spring.kafka.producer.bootstrap-servers=kafka-service:9092
    spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
    spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
    spring.kafka.producer.topic=caterer-topic
