version: '3.1'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    hostname: mongo
    ports:
      - 27017:27017
    volumes:
      - $HOME/mongo:/data/db
    healthcheck:
      test: "exit 0"
  redis:
    image: redis
    container_name: redis
    restart: always
    hostname: redis
    ports:
      - "6379:6379"